export const stockList = [
  { ticker: "MGLU3", name: "Magazine Luiza" },
  { ticker: "PETZ3", name: "Petz" },
  { ticker: "PETR4", name: "Petrobras" },
  { ticker: "HAPV3", name: "Hapvida" },
  { ticker: "CPLE6", name: "Copel" },
  { ticker: "BBDC4", name: "Banco Bradesco" },
  { ticker: "COGN3", name: "Cogna" },
  { ticker: "B3SA3", name: "B3" },
  { ticker: "CVCB3", name: "CVC" },
  { ticker: "VALE3", name: "Vale" },
  { ticker: "EQTL3", name: "Equatorial Energia" },
  { ticker: "PCAR3", name: "Grupo Pão de Açúcar" },
  { ticker: "ITUB4", name: "Ita\u00fa Unibanco" },
  { ticker: "ABEV3", name: "Ambev" },
  { ticker: "SEQL3", name: "Sequoia Log\u00edstica" },
  { ticker: "CMIG4", name: "CEMIG" },
  { ticker: "USIM5", name: "Usiminas" },
  { ticker: "RAIZ4", name: "Ra\u00edzen" },
  { ticker: "AZUL4", name: "Azul" },
  { ticker: "OIBR3", name: "Oi" },
  { ticker: "PETR3", name: "Petrobras" },
  { ticker: "AMER3", name: "Americanas" },
  { ticker: "BBAS3", name: "Banco do Brasil" },
  { ticker: "LREN3", name: "Lojas Renner" },
  { ticker: "GGBR4", name: "Gerdau" },
  { ticker: "CIEL3", name: "Cielo" },
  { ticker: "MRVE3", name: "MRV" },
  { ticker: "ITSA4", name: "Ita\u00fasa" },
  { ticker: "RADL3", name: "RaiaDrogasil" },
  { ticker: "SOMA3", name: "Grupo Soma" },
  { ticker: "RENT3", name: "Localiza" },
  { ticker: "GOLL4", name: "GOL" },
  { ticker: "ASAI3", name: "Assa\u00ed" },
  { ticker: "CYRE3", name: "Cyrela" },
  { ticker: "IFCM3", name: "Infracommerce" },
  { ticker: "EGIE3", name: "Engie" },
  { ticker: "GOAU4", name: "Metal\u00fargica Gerdau" },
  { ticker: "QUAL3", name: "Qualicorp" },
  { ticker: "RAIL3", name: "Rumo" },
  { ticker: "NEOE3", name: "Neoenergia" },
  { ticker: "CSNA3", name: "Sider\u00fargica Nacional" },
  { ticker: "CMIN3", name: "CSN Minera\u00e7\u00e3o" },
  { ticker: "PRIO3", name: "PetroRio" },
  { ticker: "MRFG3", name: "Marfrig" },
  { ticker: "CPLE3", name: "Copel" },
  { ticker: "BEEF3", name: "Minerva" },
  { ticker: "NTCO3", name: "Natura" },
  { ticker: "RDOR3", name: "Rede D'Or" },
  { ticker: "VAMO3", name: "Grupo Vamos" },
  { ticker: "STBP3", name: "Santos Brasil" },
  { ticker: "BRFS3", name: "BRF" },
  { ticker: "CSAN3", name: "Cosan" },
  { ticker: "ALPA4", name: "Alpargatas" },
  { ticker: "WEGE3", name: "WEG" },
  { ticker: "ECOR3", name: "EcoRodovias" },
  { ticker: "TOTS3", name: "Totvs" },
  { ticker: "TIMS3", name: "TIM" },
  { ticker: "BHIA3", name: "Casas Bahia" },
  { ticker: "JBSS3", name: "JBS" },
  { ticker: "BRAP4", name: "Bradespar" },
  { ticker: "ELET3", name: "Eletrobras" },
  { ticker: "EMBR3", name: "Embraer" },
  { ticker: "SBSP3", name: "Sabesp" },
  { ticker: "CCRO3", name: "Grupo CCR" },
  { ticker: "ENEV3", name: "Eneva" },
  { ticker: "CEAB3", name: "C&A" },
  { ticker: "SIMH3", name: "Simpar" },
  { ticker: "AURE3", name: "Auren Energia" },
  { ticker: "POMO4", name: "Marcopolo" },
  { ticker: "RRRP3", name: "3R Petroleum" },
  { ticker: "HBSA3", name: "Hidrovias do Brasil" },
  { ticker: "ANIM3", name: "\u00c2nima Educa\u00e7\u00e3o" },
  { ticker: "VBBR3", name: "Vibra Energia" },
  { ticker: "MULT3", name: "Multiplan" },
  { ticker: "SUZB3", name: "Suzano" },
  { ticker: "PDGR3", name: "PDG Realty" },
  { ticker: "RAPT4", name: "Randon" },
  { ticker: "ALOS3", name: "ALOS3" },
  { ticker: "LWSA3", name: "Locaweb" },
  { ticker: "HYPE3", name: "Hypera" },
  { ticker: "BBDC3", name: "Banco Bradesco" },
  { ticker: "RECV3", name: "PetroRec\u00f4ncavo" },
  { ticker: "AESB3", name: "AES Brasil" },
  { ticker: "CPFE3", name: "CPFL Energia" },
  { ticker: "TRPL4", name: "Transmiss\u00e3o Paulista" },
  { ticker: "YDUQ3", name: "YDUQS" },
  { ticker: "CBAV3", name: "CBA" },
  { ticker: "GMAT3", name: "Grupo Mateus" },
  { ticker: "JHSF3", name: "JHSF" },
  { ticker: "SLCE3", name: "SLC Agr\u00edcola" },
  { ticker: "BBSE3", name: "BB Seguridade" },
  { ticker: "LJQQ3", name: "Lojas Quero-Quero" },
  { ticker: "CSMG3", name: "COPASA" },
  { ticker: "DXCO3", name: "Dexco" },
  { ticker: "CRFB3", name: "Carrefour Brasil" },
  { ticker: "EZTC3", name: "EZTEC" },
  { ticker: "BPAN4", name: "Banco Pan" },
  { ticker: "SMFT3", name: "Smart Fit" },
  { ticker: "FLRY3", name: "Fleury" },
  { ticker: "TEND3", name: "Construtora Tenda" },
  { ticker: "GUAR3", name: "Guararapes" },
  { ticker: "MLAS3", name: "Multilaser" },
  { ticker: "CASH3", name: "M\u00e9liuz" },
  { ticker: "UGPA3", name: "Ultrapar" },
  { ticker: "SMTO3", name: "S\u00e3o Martinho" },
  { ticker: "AZEV4", name: "Azevedo & Travassos" },
  { ticker: "ARZZ3", name: "Arezzo" },
  { ticker: "ONCO3", name: "Oncocl\u00ednicas" },
  { ticker: "ENAT3", name: "Enauta" },
  { ticker: "SBFG3", name: "Grupo SBF" },
  { ticker: "DIRR3", name: "Direcional" },
  { ticker: "CURY3", name: "Cury" },
  { ticker: "VIVT3", name: "Vivo" },
  { ticker: "CXSE3", name: "Caixa Seguridade" },
  { ticker: "MOVI3", name: "Movida" },
  { ticker: "PSSA3", name: "Porto Seguro" },
  { ticker: "CLSA3", name: "ClearSale" },
  { ticker: "BRKM5", name: "Braskem" },
  { ticker: "ODPV3", name: "Odontoprev" },
  { ticker: "SRNA3", name: "SRNA3" },
  { ticker: "MILS3", name: "Mills" },
  { ticker: "VIVA3", name: "Vivara" },
  { ticker: "GGPS3", name: "GPS" },
  { ticker: "SOJA3", name: "Boa Safra Sementes" },
  { ticker: "INTB3", name: "Intelbras" },
  { ticker: "POSI3", name: "Positivo" },
  { ticker: "SAPR4", name: "Sanepar" },
  { ticker: "OPCT3", name: "OceanPact" },
  { ticker: "GFSA3", name: "Gafisa" },
  { ticker: "RCSL4", name: "Recrusul" },
  { ticker: "BRSR6", name: "Banrisul" },
  { ticker: "MATD3", name: "Mater Dei" },
  { ticker: "KEPL3", name: "Kepler Weber" },
  { ticker: "GRND3", name: "Grendene" },
  { ticker: "TTEN3", name: "3tentos" },
  { ticker: "ZAMP3", name: "Zamp" },
  { ticker: "MYPK3", name: "Iochpe-Maxion" },
  { ticker: "AMBP3", name: "Ambipar" },
  { ticker: "MTRE3", name: "Mitre Realty" },
  { ticker: "MDNE3", name: "Moura Dubeux" },
  { ticker: "RCSL3", name: "Recrusul" },
  { ticker: "ELET6", name: "Eletrobras" },
  { ticker: "JALL3", name: "Jalles Machado" },
  { ticker: "ESPA3", name: "Espa\u00e7olaser" },
  { ticker: "ARML3", name: "Armac" },
  { ticker: "PGMN3", name: "Pague Menos" },
  { ticker: "IRBR3", name: "IRB Brasil RE" },
  { ticker: "BRIT3", name: "Brisanet" },
  { ticker: "AERI3", name: "Aeris Energy" },
  { ticker: "RANI3", name: "Irani" },
  { ticker: "FESA4", name: "Ferbasa" },
  { ticker: "PORT3", name: "Wilson Sons" },
  { ticker: "ABCB4", name: "Banco ABC Brasil" },
  { ticker: "CAML3", name: "Camil Alimentos" },
  { ticker: "AGRO3", name: "BrasilAgro" },
  { ticker: "PLPL3", name: "Plano&Plano" },
  { ticker: "ENJU3", name: "Enjoei" },
  { ticker: "VULC3", name: "Vulcabras" },
  { ticker: "EVEN3", name: "Even" },
  { ticker: "KRSA3", name: "Kora Sa\u00fade" },
  { ticker: "HBRE3", name: "HBR Realty" },
  { ticker: "SEER3", name: "Ser Educacional" },
  { ticker: "MDIA3", name: "M. Dias Branco" },
  { ticker: "PFRM3", name: "Profarma" },
  { ticker: "KLBN4", name: "Klabin" },
  { ticker: "MBLY3", name: "Mobly" },
  { ticker: "AMAR3", name: "Lojas Marisa" },
  { ticker: "TUPY3", name: "Tupy" },
  { ticker: "LAVV3", name: "Lavvi Incorporadora" },
  { ticker: "TASA4", name: "Taurus" },
  { ticker: "TRIS3", name: "Trisul" },
  { ticker: "VVEO3", name: "Viveo" },
  { ticker: "PTBL3", name: "Portobello" },
  { ticker: "PINE4", name: "PINE" },
  { ticker: "SHUL4", name: "Schulz" },
  { ticker: "BIOM3", name: "Biomm" },
  { ticker: "DASA3", name: "Dasa" },
  { ticker: "RNEW4", name: "Renova Energia" },
  { ticker: "PRNR3", name: "Priner" },
  { ticker: "BMGB4", name: "Banco BMG" },
  { ticker: "NGRD3", name: "Neogrid" },
  { ticker: "UNIP6", name: "Unipar" },
  { ticker: "HBOR3", name: "Helbor" },
  { ticker: "CMIG3", name: "CEMIG" },
  { ticker: "PNVL3", name: "Dimed" },
  { ticker: "WIZC3", name: "Wiz Solu\u00e7\u00f5es" },
  { ticker: "VITT3", name: "Vittia" },
  { ticker: "BMOB3", name: "Bemobi" },
  { ticker: "LIGT3", name: "Light" },
  { ticker: "SYNE3", name: "SYN" },
  { ticker: "ROMI3", name: "Ind\u00fastrias ROMI" },
  { ticker: "ITUB3", name: "Ita\u00fa Unibanco" },
  { ticker: "LEVE3", name: "Mahle Metal Leve" },
  { ticker: "AGXY3", name: "AgroGalaxy" },
  { ticker: "MEAL3", name: "IMC Alimenta\u00e7\u00e3o" },
  { ticker: "SANB4", name: "Banco Santander" },
  { ticker: "AZEV3", name: "Azevedo & Travassos" },
  { ticker: "RSID3", name: "Rossi Residencial" },
  { ticker: "JSLG3", name: "JSL" },
  { ticker: "TECN3", name: "Technos" },
  { ticker: "OIBR4", name: "Oi" },
  { ticker: "USIM3", name: "Usiminas" },
  { ticker: "VLID3", name: "Valid" },
  { ticker: "BLAU3", name: "Blau Farmac\u00eautica" },
  { ticker: "KLBN3", name: "Klabin" },
  { ticker: "DMVF3", name: "D1000 Varejo Farma" },
  { ticker: "ETER3", name: "Eternit" },
  { ticker: "FRAS3", name: "Fras-le" },
  { ticker: "TAEE4", name: "Taesa" },
  { ticker: "ORVR3", name: "Orizon" },
  { ticker: "CSED3", name: "Cruzeiro do Sul Educacional" },
  { ticker: "SAPR3", name: "Sanepar" },
  { ticker: "TRAD3", name: "Traders Club" },
  { ticker: "CAMB3", name: "Cambuci" },
  { ticker: "SANB3", name: "Banco Santander" },
  { ticker: "PMAM3", name: "Paranapanema" },
  { ticker: "LUPA3", name: "Lupatech" },
  { ticker: "ALLD3", name: "Allied" },
  { ticker: "TGMA3", name: "Tegma" },
  { ticker: "LOGG3", name: "LOG CP" },
  { ticker: "LPSB3", name: "Lopes" },
  { ticker: "AALR3", name: "Allian\u00e7a" },
  { ticker: "DESK3", name: "Desktop" },
  { ticker: "SGPS3", name: "Springs" },
  { ticker: "FIQE3", name: "Unifique" },
  { ticker: "UCAS3", name: "Unicasa" },
  { ticker: "POMO3", name: "Marcopolo" },
  { ticker: "ELMD3", name: "Eletromidia" },
  { ticker: "ALPK3", name: "Estapar" },
  { ticker: "INEP3", name: "Inepar" },
  { ticker: "EUCA4", name: "Eucatex" },
  { ticker: "TAEE3", name: "Taesa" },
  { ticker: "JFEN3", name: "Jo\u00e3o Fortes" },
  { ticker: "ITSA3", name: "Ita\u00fasa" },
  { ticker: "MELK3", name: "Melnick" },
  { ticker: "TFCO4", name: "Track & Field" },
  { ticker: "EMAE4", name: "EMAE" },
  { ticker: "SHOW3", name: "Time For Fun" },
  { ticker: "NINJ3", name: "GetNinjas" },
  { ticker: "GGBR3", name: "Gerdau" },
  { ticker: "TCSA3", name: "Tecnisa" },
  { ticker: "INEP4", name: "Inepar" },
  { ticker: "RNEW3", name: "Renova Energia" },
  { ticker: "CSUD3", name: "CSU Cardsystem" },
  { ticker: "PDTC3", name: "Padtec" },
  { ticker: "BRAP3", name: "Bradespar" },
  { ticker: "LVTC3", name: "WDC Networks" },
  { ticker: "DEXP3", name: "Dexxos" },
  { ticker: "GOAU3", name: "Metal\u00fargica Gerdau" },
  { ticker: "LAND3", name: "Terra Santa" },
  { ticker: "WEST3", name: "Westwing" },
  { ticker: "ALUP4", name: "Alupar" },
  { ticker: "ALUP3", name: "Alupar" },
  { ticker: "LOGN3", name: "Log-In" },
  { ticker: "VIVR3", name: "Viver" },
  { ticker: "CTSA4", name: "Santanense" },
  { ticker: "BOBR4", name: "Bombril" },
  { ticker: "RAPT3", name: "Randon" },
  { ticker: "TPIS3", name: "Triunfo" },
  { ticker: "NUTR3", name: "Nutriplant" },
  { ticker: "OFSA3", name: "Ourofino Sa\u00fade Animal" },
  { ticker: "ATOM3", name: "ATOM" },
  { ticker: "DOTZ3", name: "Dotz" },
  { ticker: "HAGA4", name: "Haga" },
  { ticker: "TASA3", name: "Taurus" },
  { ticker: "UNIP3", name: "Unipar" },
  { ticker: "CLSC4", name: "Celesc" },
  { ticker: "OSXB3", name: "OSX Brasil" },
  { ticker: "COCE5", name: "Coelce" },
  { ticker: "CEBR6", name: "CEB" },
  { ticker: "IGTI3", name: "Iguatemi" },
  { ticker: "APER3", name: "Alper" },
  { ticker: "BRSR3", name: "Banrisul" },
  { ticker: "EALT4", name: "Electro A\u00e7o Altona" },
  { ticker: "PLAS3", name: "Plascar" },
  { ticker: "BEES3", name: "Banestes" },
  { ticker: "BPAC5", name: "Banco BTG Pactual" },
  { ticker: "ENGI4", name: "Energisa" },
  { ticker: "ATMP3", name: "Atma" },
  { ticker: "CGRA3", name: "Grazziotin" },
  { ticker: "FIEI3", name: "Fica" },
  { ticker: "MAPT4", name: "Cemepe" },
  { ticker: "BAZA3", name: "Banco da Amaz\u00f4nia" },
  { ticker: "CRPG5", name: "Tronox Pigmentos" },
  { ticker: "SCAR3", name: "S\u00e3o Carlos" },
  { ticker: "CTKA4", name: "Karsten" },
  { ticker: "BPAC3", name: "Banco BTG Pactual" },
  { ticker: "RPMG3", name: "Refinaria de Manguinhos" },
  { ticker: "BRKM3", name: "Braskem" },
  { ticker: "CEBR3", name: "CEB" },
  { ticker: "MNPR3", name: "Minupar" },
  { ticker: "BMEB4", name: "Banco Mercantil do Brasil" },
  { ticker: "VSTE3", name: "LE LIS BLANC" },
  { ticker: "MTSA4", name: "METISA" },
  { ticker: "CTNM4", name: "Coteminas" },
  { ticker: "CGRA4", name: "Grazziotin" },
  { ticker: "ENGI3", name: "Energisa" },
  { ticker: "FHER3", name: "Fertilizantes Heringer" },
  { ticker: "BEES4", name: "Banestes" },
  { ticker: "WHRL3", name: "Whirlpool" },
  { ticker: "CEBR5", name: "CEB" },
  { ticker: "AVLL3", name: "Alphaville" },
  { ticker: "EPAR3", name: "Embpar Participa\u00e7\u00f5es" },
  { ticker: "WHRL4", name: "Whirlpool" },
  { ticker: "NEXP3", name: "Brasil Brokers" },
  { ticker: "RDNI3", name: "RNI" },
  { ticker: "PINE3", name: "PINE" },
  { ticker: "CTSA3", name: "Santanense" },
  { ticker: "MGEL4", name: "Mangels" },
  { ticker: "NORD3", name: "Nordon" },
  { ticker: "PTNT4", name: "Pettenati" },
  { ticker: "REDE3", name: "Rede Energia" },
  { ticker: "CEEB3", name: "COELBA" },
  { ticker: "CRPG6", name: "Tronox Pigmentos" },
  { ticker: "CEDO3", name: "Cedro T\u00eaxtil" },
  { ticker: "RPAD3", name: "Alfa Holdings" },
  { ticker: "TRPL3", name: "Transmiss\u00e3o Paulista" },
  { ticker: "SNSY3", name: "Sansuy" },
  { ticker: "WLMM4", name: "WLM" },
  { ticker: "ALPA3", name: "Alpargatas" },
  { ticker: "BDLL4", name: "Bardella" },
  { ticker: "IGTI4", name: "Iguatemi" },
  { ticker: "EQMA3B", name: "Equatorial Maranh\u00e3o" },
  { ticker: "PTNT3", name: "Pettenati" },
  { ticker: "CGAS5", name: "Comg\u00e1s" },
  { ticker: "MNDL3", name: "Mundial" },
  { ticker: "BGIP4", name: "Banese" },
  { ticker: "TELB4", name: "Telebras" },
  { ticker: "BNBR3", name: "Banco do Nordeste" },
  { ticker: "ENMT4", name: "Energisa MT" },
  { ticker: "HBTS5", name: "Habitasul" },
  { ticker: "BGIP3", name: "Banese" },
  { ticker: "BDLL3", name: "Bardella" },
  { ticker: "BAHI3", name: "Bahema" },
  { ticker: "CTNM3", name: "Coteminas" },
  { ticker: "HETA4", name: "Hercules" },
  { ticker: "SNSY5", name: "Sansuy" },
  { ticker: "BMKS3", name: "Monark" },
  { ticker: "MOAR3", name: "Monteiro Aranha" },
  { ticker: "RSUL4", name: "Metal\u00fargica Riosulense" },
  { ticker: "EKTR4", name: "Elektro" },
  { ticker: "GEPA4", name: "Rio Paranapanema Energia" },
  { ticker: "DEXP4", name: "Dexxos" },
  { ticker: "EQPA3", name: "Equatorial Energia Par\u00e1" },
  { ticker: "CGAS3", name: "Comg\u00e1s" },
  { ticker: "ELET5", name: "Eletrobras" },
  { ticker: "BMEB3", name: "Banco Mercantil do Brasil" },
  { ticker: "EUCA3", name: "Eucatex" },
  { ticker: "BRSR5", name: "Banrisul" },
  { ticker: "FESA3", name: "Ferbasa" },
  { ticker: "BMIN4", name: "Banco Mercantil de Investimentos" },
  { ticker: "BSLI4", name: "Banco de Bras\u00edlia" },
  { ticker: "DOHL4", name: "D\u00f6hler" },
  { ticker: "HAGA3", name: "Haga" },
  { ticker: "MAPT3", name: "Cemepe" },
  { ticker: "GEPA3", name: "Rio Paranapanema Energia" },
  { ticker: "CSRN3", name: "COSERN" },
  { ticker: "JOPA3", name: "Josapar" },
  { ticker: "HOOT4", name: "Hot\u00e9is Othon" },
  { ticker: "TELB3", name: "Telebras" },
  { ticker: "DMFN3", name: "DM Financeira" },
  { ticker: "BALM3", name: "Baumer" },
  { ticker: "RPAD5", name: "Alfa Holdings" },
  { ticker: "FRTA3", name: "Pomi Frutas" },
  { ticker: "CEDO4", name: "Cedro T\u00eaxtil" },
  { ticker: "AFLT3", name: "Afluente T" },
  { ticker: "TEKA3", name: "Teka" },
  { ticker: "BAUH4", name: "Excelsior" },
  { ticker: "ENMT3", name: "Energisa MT" },
  { ticker: "CALI3", name: "Adolpho Lindenberg" },
  { ticker: "EALT3", name: "Electro A\u00e7o Altona" },
  { ticker: "RPAD6", name: "Alfa Holdings" },
  { ticker: "DTCY3", name: "Dtcom" },
  { ticker: "PEAB3", name: "Participa\u00e7\u00f5es Alian\u00e7a da Bahia" },
  { ticker: "PEAB4", name: "Participa\u00e7\u00f5es Alian\u00e7a da Bahia" },
  { ticker: "ESTR4", name: "Estrela" },
  { ticker: "UNIP5", name: "Unipar" },
  { ticker: "AHEB6", name: "S\u00e3o Paulo Turismo" },
  { ticker: "AHEB3", name: "S\u00e3o Paulo Turismo" },
  { ticker: "BSLI3", name: "Banco de Bras\u00edlia" },
  { ticker: "MWET4", name: "Wetzel" },
  { ticker: "LIPR3", name: "Eletropar" },
  { ticker: "CPLE5", name: "Copel" },
  { ticker: "CSRN6", name: "COSERN" },
  { ticker: "CBEE3", name: "Ampla Energia" },
  { ticker: "MERC4", name: "Mercantil do Brasil Financeira" },
  { ticker: "CLSC3", name: "Celesc" },
  { ticker: "SOND5", name: "Sondot\u00e9cnica" },
  { ticker: "GSHP3", name: "General Shopping & Outlets" },
  { ticker: "SOND6", name: "Sondot\u00e9cnica" },
  { ticker: "CSRN5", name: "COSERN" },
  { ticker: "CEED4", name: "CEEE D" },
  { ticker: "MWET3", name: "Wetzel" },
  { ticker: "BALM4", name: "Baumer" },
  { ticker: "DOHL3", name: "D\u00f6hler" },
  { ticker: "MRSA6B", name: "MRS Log\u00edstica" },
  { ticker: "USIM6", name: "Usiminas" },
  { ticker: "EKTR3", name: "Elektro" },
  { ticker: "MRSA5B", name: "MRS Log\u00edstica" },
  { ticker: "MRSA3B", name: "MRS Log\u00edstica" },
  { ticker: "LUXM4", name: "Trevisa" },
  { ticker: "EMAE3", name: "EMAE" },
  { ticker: "CTKA3", name: "Karsten" },
  { ticker: "FRIO3", name: "Metalfrio" },
  { ticker: "TKNO4", name: "Tekno" },
  { ticker: "BRIV4", name: "Alfa Investimento" },
  { ticker: "CRIV4", name: "Alfa Financeira" },
  { ticker: "CRPG3", name: "Tronox Pigmentos" },
  { ticker: "BRGE3", name: "Cons\u00f3rcio Alfa" },
  { ticker: "BRIV3", name: "Alfa Investimento" },
  { ticker: "BRGE6", name: "Cons\u00f3rcio Alfa" },
  { ticker: "PATI3", name: "Panatl\u00e2ntica" },
  { ticker: "EQPA6", name: "Equatorial Energia Par\u00e1" },
  { ticker: "CRIV3", name: "Alfa Financeira" },
  { ticker: "BRKM6", name: "Braskem" },
  { ticker: "BRGE12", name: "Cons\u00f3rcio Alfa" },
  { ticker: "BRGE11", name: "Cons\u00f3rcio Alfa" },
  { ticker: "GPAR3", name: "CELGPAR" },
  { ticker: "PATI4", name: "Panatl\u00e2ntica" },
  { ticker: "TEKA4", name: "Teka" },
  { ticker: "MSPA4", name: "Melhoramentos" },
  { ticker: "WLMM3", name: "WLM" },
  { ticker: "EQPA7", name: "Equatorial Energia Par\u00e1" },
  { ticker: "BRGE5", name: "Cons\u00f3rcio Alfa" },
  { ticker: "BRGE8", name: "Cons\u00f3rcio Alfa" },
  { ticker: "MSPA3", name: "Melhoramentos" },
  { ticker: "CEEB5", name: "COELBA" },
  { ticker: "BRGE7", name: "Cons\u00f3rcio Alfa" },
  { ticker: "EQPA5", name: "Equatorial Energia Par\u00e1" },
  { ticker: "JOPA4", name: "Josapar" },
  { ticker: "BMIN3", name: "Banco Mercantil de Investimentos" },
  { ticker: "COCE3", name: "Coelce" },
  { ticker: "CEGR3", name: "Naturgy (CEG)" },
  { ticker: "ESTR3", name: "Estrela" },
  { ticker: "AHEB5", name: "S\u00e3o Paulo Turismo" },
  { ticker: "CEED3", name: "CEEE D" },
  { ticker: "CSAB3", name: "Cia. de Seg. Alian\u00e7a da Bahia" },
  { ticker: "CSAB4", name: "Cia. de Seg. Alian\u00e7a da Bahia" },
  { ticker: "MEGA3", name: "OMEGA ENERGIA S.A." },
  { ticker: "SQIA3", name: "Sinqia" },
  { ticker: "ALSO3", name: "Aliansce Sonae" },
  { ticker: "BRPR3", name: "BR Properties" },
  { ticker: "MTSA3", name: "METISA" },
  { ticker: "SLED4", name: "Saraiva" },
  { ticker: "SLED3", name: "Saraiva" },
  { ticker: "VIIA3", name: "VIIA3" },
  { ticker: "ENBR3", name: "EDP Brasil" },
  { ticker: "BOAS3", name: "Boa Vista" },
  { ticker: "MODL3", name: "Banco Modal" },
  { ticker: "MERC3", name: "Mercantil do Brasil Financeira" },
  { ticker: "CRDE3", name: "CRDE3" },
  { ticker: "IGBR3", name: "IGB Eletr\u00f4nica" },
  { ticker: "ODER4", name: "Conservas Oderich" },
  { ticker: "PARD3", name: "Hermes Pardini" },
  { ticker: "CASN3", name: "CASAN" },
  { ticker: "WIZS3", name: "WIZS3" },
  { ticker: "LLIS3", name: "LLIS3" },
  { ticker: "BRML3", name: "BRMalls" },
  { ticker: "DMMO3", name: "Dommo Energia" },
  { ticker: "GETT3", name: "Getnet" },
  { ticker: "GETT4", name: "Getnet" },
  { ticker: "SULA4", name: "SulAm\u00e9rica" },
  { ticker: "SULA3", name: "SulAm\u00e9rica" },
  { ticker: "CEPE5", name: "CELPE" },
  { ticker: "TCNO4", name: "Tecnosolo" },
  { ticker: "TCNO3", name: "Tecnosolo" },
  { ticker: "CEPE6", name: "CELPE" },
  { ticker: "BKBR3", name: "BKBR3" },
  { ticker: "MTIG4", name: "Metalgr\u00e1fica Igua\u00e7u" },
  { ticker: "BLUT4", name: "Blue Tech Solutions" },
  { ticker: "BLUT3", name: "Blue Tech Solutions" },
  { ticker: "MODL4", name: "Banco Modal" },
  { ticker: "CARD3", name: "CARD3" },
  { ticker: "SHUL3", name: "Schulz" },
  { ticker: "FIGE3", name: "Investimentos Bemge" },
  { ticker: "FNCN3", name: "FNCN3" },
  { ticker: "HETA3", name: "Hercules" },
  { ticker: "LCAM3", name: "Locamerica" },
  { ticker: "BIDI4", name: "Banco Inter" },
  { ticker: "BIDI3", name: "Banco Inter" },
  { ticker: "EEEL4", name: "CEEE GT" },
  { ticker: "EEEL3", name: "CEEE GT" },
  { ticker: "BBRK3", name: "BBRK3" },
  { ticker: "SOND3", name: "Sondot\u00e9cnica" },
  { ticker: "CESP6", name: "CESP" },
  { ticker: "CESP3", name: "CESP" },
  { ticker: "CESP5", name: "CESP" },
  { ticker: "ECPR4", name: "Encorpar" },
  { ticker: "MOSI3", name: "Mosaico" },
  { ticker: "POWE3", name: "Focus Energia" },
  { ticker: "ECPR3", name: "Encorpar" },
  { ticker: "GNDI3", name: "NotreDame Interm\u00e9dica" },
  { ticker: "LAME4", name: "Lojas Americanas" },
  { ticker: "LAME3", name: "Lojas Americanas" },
  { ticker: "OMGE3", name: "Omega Gera\u00e7\u00e3o" },
  { ticker: "IGTA3", name: "IGTA3" },
  { ticker: "JPSA3", name: "JPSA3" },
  { ticker: "BRDT3", name: "BRDT3" },
  { ticker: "JBDU4", name: "JBDU4" },
  { ticker: "JBDU3", name: "JBDU3" },
  { ticker: "HGTX3", name: "Hering" },
  { ticker: "CCPR3", name: "CCPR3" },
  { ticker: "DTEX3", name: "DTEX3" },
  { ticker: "VVAR3", name: "VVAR3" },
  { ticker: "PNVL4", name: "Dimed" },
  { ticker: "TESA3", name: "Terra Santa" },
  { ticker: "BTOW3", name: "BTOW3" },
  { ticker: "LINX3", name: "Linx" },
  { ticker: "BTTL3", name: "BTTL3" },
  { ticker: "GPCP3", name: "GPCP3" },
  { ticker: "GPCP4", name: "GPCP4" },
  { ticker: "SMLS3", name: "Smiles" },
  { ticker: "MMXM3", name: "MMX Minera\u00e7\u00e3o" },
  { ticker: "BSEV3", name: "Biosev" },
  { ticker: "CNTO3", name: "CNTO3" },
  { ticker: "TIET4", name: "AES Tiet\u00ea Energia" },
  { ticker: "TIET3", name: "AES Tiet\u00ea Energia" },
  { ticker: "CORR4", name: "Corr\u00eaa Ribeiro" },
  { ticker: "CEPE3", name: "CELPE" },
  { ticker: "CALI4", name: "Adolpho Lindenberg" },
  { ticker: "SNSY6", name: "Sansuy" },
  { ticker: "CASN4", name: "CASAN" },
  { ticker: "BPAR3", name: "Banpar\u00e1" },
  { ticker: "APTI4", name: "Aliperti" },
  { ticker: "VSPT3", name: "FCA" },
  { ticker: "MTIG3", name: "Metalgr\u00e1fica Igua\u00e7u" },
  { ticker: "FIGE4", name: "Investimentos Bemge" },
  { ticker: "LUXM3", name: "Trevisa" },
  { ticker: "TKNO3", name: "Tekno" },
  { ticker: "COCE6", name: "Coelce" },
  { ticker: "MGEL3", name: "Mangels" },
  { ticker: "CTSA8", name: "Santanense" },
  { ticker: "MMAQ4", name: "Minasm\u00e1quinas" }]